### PR TITLE
Rhbz1314973 refactor kernelver detection v3

### PR DESCRIPTION
**Pull request by DaveWysochanskiRH**
This is hopefully the last version of these patches.
Fixes
1. Problem with create.wsgi reported after testing by Patrik Helia
[Fri Mar 11 08:24:48 2016] [error] [client 10.34.24.100] mod_wsgi (pid=5396): Exception occurred processing WSGI script '/usr/share/retrace-server/create.wsgi'. [Fri Mar 11 08:24:48 2016] [error] [client 10.34.24.100] Traceback (most recent call last): 
[Fri Mar 11 08:24:48 2016] [error] [client 10.34.24.100] File "/usr/share/retrace-server/create.wsgi", line 199, in application 
[Fri Mar 11 08:24:48 2016] [error] [client 10.34.24.100] strip_vmcore(os.path.join(crashdir, "vmcore")) 
[Fri Mar 11 08:24:48 2016] [error] [client 10.34.24.100] NameError: global name 'strip_vmcore' is not defined

2. Small problem with strip_vmcore incorrectly calling prepare_debuginfo
    There was a small problem with strip_vmcore which incorrectly was calling prepare_debuginfo.
    This would result in the following error in the retrace_log:
     2016-03-11 06:03:59 prepare_debuginfo failed: execv() arg 2 must contain only strings

### CODE REVIEW

**Comment by DaveWysochanskiRH** [comment]
Please note: I tested this patch set on top of the other patches for the other two pull requests.  Here is my full gitlog of how I tested:
 git log --oneline | head
afaa618 Fix small problem with strip_vmcore calling prepare_debuginfo.
97a6a5a Avoid calling prepare_debuginfo from retrace-server-interact after kernel version detection.
61df794 Move prepare_debuginfo and strip_vmcore inside RetraceTask
621a036 Add vmlinux file inside RetraceTask
34e5f2b Enforce uniform mode bits for almost all RetraceTask files
492066c Fix incorrect group permissions when writing RetraceServer files especially with interactive mode
f3703d6 Fix retrace-server-worker --restart backtrace due to unwriteable retrace_log
2fc0d7d Merge pull request #93 from patriczek/master
a85ff0a Change license address

**Comment by DaveWysochanskiRH** [comment]
FWIW, I just pushed my test branch, all-fixes-rhbz1314897-rhbz1313011-rhbz1314973-v3

**Comment by patriczek** [comment]
It's work for me.

I sended vmcore to retrace server and get backtrace correctly

**Comment by jfilak** [comment]
Thank you all! I've pushed these commits (there was a conflict, so I rebased Dave's patches):
  da801cd Fix small problem with strip_vmcore calling prepare_debuginfo.
  75a96f7 Avoid calling prepare_debuginfo from retrace-server-interact after kernel version detection.
  12bae97 Move prepare_debuginfo and strip_vmcore inside RetraceTask
  102c315 Add vmlinux file inside RetraceTask

**Pull request closed without merging**
