### PR TITLE
Rework manager page

### PR DESCRIPTION
**Pull request by DaveWysochanskiRH**
These changes rework the manager page to be a bit cleaner.  I though of going further with these, such as adding a small navigation bar on the left side of the page, but I think this is enough for now.

Short list of changes:
1. "FTP files" list removed from the first page, added link at the top
* FTP based vmcore file tasks are very low utilization now
* It takes time to load the page and probably does not make sense to have this on the front page
* This was always somewhat of a hack - if you reload the page you'll see a "Available tasks" table header pop up briefly before "FTP files"

2. Add border around the "Create vmcore task" area

3. Make "Finished Tasks" take up the full page.
* Previously the page was split, and a lot of space was wasted
* Now "Running Tasks" and "Available Tasks" only show up above "Finished tasks" if any exist.

4. On the per task manager page, remove about 1" of whitespace from right side of page

### CODE REVIEW

**Comment by michalfabik** [comment]
Hi Dave, are you planning on adding anything more to this PR?

**Comment by DaveWysochanskiRH** [comment]
> Hi Dave, are you planning on adding anything more to this PR?

I had asked our internal group for feedback but I didn't get any so far after about a week.

Also I was considering looking at CSS again to see if I can make it even better with a pulldown menu, but I'm not sure about it so maybe I shouldn't delay this set.

Probably if you think it is good enough for now it may be good enough of a PR as it is.  I have this on our dev server if you want to take a look at the new pages - it is on top of the latest upstream now (1.22.2-1)

**Comment by michalfabik** [comment]
>  I have this on our dev server if you want to take a look at the new pages - it is on top of the latest upstream now (1.22.2-1)  
  
Sure! I'd swear I saw you post a link somewhere but can't seem to find it now (am I imagining things?).

**Comment by DaveWysochanskiRH** [comment]
> > I have this on our dev server if you want to take a look at the new pages - it is on top of the latest upstream now (1.22.2-1)
> 
> Sure! I'd swear I saw you post a link somewhere but can't seem to find it now (am I imagining things?).

@michalfabik I sent you an email to your redhat address

**Comment by mzidek-gh** [comment]
The only thing I find a bit confusing is that the link on top of the page "Create vmcore task (kernel memory dump) - file on FTP" feels like clicking on it would create some vmcore task, but it only lists files. So maybe the link should start with word such as "List ..." or "Show ..." (Show FTP files, "Show FTP files" or maybe just "FTP files") . Othewise LGTM.

**Comment by DaveWysochanskiRH** [comment]
> Hi @DaveWysochanskiRH
> 
> The only thing I find a bit confusing is that the link on top of the page "Create vmcore task (kernel memory dump) - file on FTP" feels like clicking on it would create some vmcore task, but it only lists files. So maybe the link should start with word such as "List ..." or "Show ..." ("List FTP files", "Show FTP files" or maybe just "FTP files") . Othewise LGTM.

I changed it to "List FTP files (create vmcore task from FTP)"

**Comment by DaveWysochanskiRH** [comment]
I think it's about as far as this will go for now, so moving out of draft.  If there's anything else you want me to fixup, let me know.  Thanks!

**Review by michalfabik — APPROVED** [review]

**Pull request merged**
