### PR TITLE
More type annotations and fixing errors

### PR DESCRIPTION
**Pull request by mgrabovsky**
I started doodling around with type annotations and mypy and accidentally fixed a few more type errors.

### CODE REVIEW

**Comment by mgrabovsky** [comment]
Found and fixed a few more, although there are still many remaining (and a couple false positives that I don't feel like dealing with right now).

It appears some of these changes were not really worth it to begin with. For instance, `repopath` defined as `Path` [in `retrace_worker.py`](https://github.com/abrt/retrace-server/pull/337/commits/0179547f0cd0c80e8b3e0056a2612376f3f6a8fb#diff-15145150e9d46bc5630e27606be82388R427) is only used as string later, `os.path.join()` would be perfectly fine here.

**Comment by michalfabik** [comment]
Looks all good to me.  
   
> It appears some of these changes were not really worth it to begin with.  
  
Well, yeah. That dawned on me pretty soon after I started messing with pathlib. My initial motivation was to use this as a sort of gentle introduction into the type annotation/checking so I figured at least there's this one purpose it might serve. Now with all the breakage, I suppose the type checks are pretty much a necessity. Oh well. Sorry guys.

**Comment by mgrabovsky** [comment]
Well, it's not a huge deal, but I suppose it's a bit annoying for our users. I, for one, am quite excited about type annotations, so I'm glad they're proliferating.

**Comment by mgrabovsky** [comment]
Rebased. Ready for review.

**Pull request merged**
