### PR TITLE
retrace: Fix class declaration order

### PR DESCRIPTION
**Pull request by michalfabik**
There were type check errors because some functions were annotated
with types/classes declared later in the code. This commit reorders
the classes as appropriate.

Signed-off-by: Michal Fabik <mfabik@redhat.com>

### CODE REVIEW

**Comment by DaveWysochanskiRH** [comment]
I guess this probably fixes this traceback:
~~~
Traceback (most recent call last):
  File "/usr/share/retrace-server/manager.wsgi", line 10, in <module>
    from retrace.retrace import (STATUS, STATUS_DOWNLOADING, STATUS_FAIL,
   File "/usr/lib/python3.6/site-packages/retrace/__init__.py", line 6, in <module>
     from . import retrace
   File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 394, in <module>
     def find_kernel_debuginfo(kernelver: KernelVer) -> Optional[Path]:
 NameError: name 'KernelVer' is not defined
~~~

**Comment by michalfabik** [comment]
> I guess this probably fixes this traceback:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/share/retrace-server/manager.wsgi", line 10, in <module>
>     from retrace.retrace import (STATUS, STATUS_DOWNLOADING, STATUS_FAIL,
>    File "/usr/lib/python3.6/site-packages/retrace/__init__.py", line 6, in <module>
>      from . import retrace
>    File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 394, in <module>
>      def find_kernel_debuginfo(kernelver: KernelVer) -> Optional[Path]:
>  NameError: name 'KernelVer' is not defined
> ```
  
  
Yeah, that was the one.

**Comment by mzidek-gh** [comment]
Can look at the results from mypy test? It looks like this patch introduced an issue there.

**Comment by ernestask** [comment]
> Can look at the results from mypy test? It looks like this patch introduced an issue there.

You might want to be more specific, because the results contain plenty of things to fix even before these changes.

**Comment by mzidek-gh** [comment]
For convenience here are the issues detected by mypy:

```
Generated files under mypy_stubs/pyfaf/
build/src/retrace/config.py: note: In class "__config":
build/src/retrace/config.py:27:9: error: Need type annotation for 'ARCH_HOSTS'
(hint: "ARCH_HOSTS: Dict[<type>, <type>] = ...")  [var-annotated]
            ARCH_HOSTS = {}
            ^
mypy_stubs/pyfaf/storage/__init__.pyi:13: note: In module imported here,
build/src/retrace/retrace.py:351: note: ... from here:
mypy_stubs/pyfaf/storage/report.pyi:10:1: error: Module 'pyfaf.utils.parse' has
no attribute 'signal2name'  [attr-defined]
    from pyfaf.utils.parse import signal2name as signal2name
    ^
build/src/retrace/retrace.py: note: In function "run_gdb":
build/src/retrace/retrace.py:288:17: error: Incompatible types in assignment
(expression has type "CompletedProcess[str]", variable has type
"CompletedProcess[bytes]")  [assignment]
            child = run(["/usr/bin/mock", "chroot", "--configdir", savedir...
                    ^
build/src/retrace/retrace.py:310:21: error: Argument 1 to "run" has
incompatible type "List[object]"; expected
"Union[Union[bytes, str], Sequence[Union[bytes, str, _PathLike[Any]]]]" 
[arg-type]
            child = run(podman_build_call, stdout=DEVNULL, stderr=DEVNULL)
                        ^
build/src/retrace/retrace.py:314:17: error: Incompatible types in assignment
(expression has type "CompletedProcess[str]", variable has type
```

I see that we had mypy failures in previous PRs as well, but I those were different.

**Comment by mzidek-gh** [comment]
Ah, wait they are actually not new. Please ignore the request for change.

**Comment by mzidek-gh** [comment]
Ok, so it does not introduce but actually fixes a bunch of the issues detected by mypy (my bad, sould read the logs better).

In terms of coding style this just moves the code around so the code is not changed in that regard.

It compiles fine. As this is not a bug fix per se, there is no need for automated tests or anything like that to be added.

**Comment by mzidek-gh** [comment]
ACK.

**Pull request merged**
