### PR TITLE
Replace yum with DNF

### PR DESCRIPTION
**Pull request by j-mracek**
The commit should provides replacement of yum by dnf. I am sorry but I didn't tested it by my self. I am not certain what import "from plugins import *" exactly do, therefore I only guess and then I try to change it according to the guess.

### CODE REVIEW

**Comment by jfilak** [comment]
Thank you for the patch. Unfortunately we cannot directly switch from yum to DNF because we must support distributions without DNF. We need to refactor the code and hide yum behind an abstraction and then add a new implementation using DNF.

**Comment by j-mracek** [comment]
@jfilak Do you need some help with refactor from my side?

**Comment by xsuchy** [comment]
@j-mracek Nope, we need to do that ourself.  Our server is on RHEL7 and we do not there DNF (well it is in EPEL, but...)

**Comment by xsuchy** [comment]
This is on hold till RHEL8

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by marusak** [comment]
Closed by  #218

**Pull request closed without merging**
