### PR TITLE
Fix reposync; update Fedora version list

### PR DESCRIPTION
**Pull request by mgrabovsky**
Second round of fixes for recent retrace server problems:
* Update Fedora plugin version list: Add F33 and remove versions older than F31.
* Fix type errors in `retrace-server-reposync-faf`.

### CODE REVIEW

**Comment by mgrabovsky** [comment]
I think this can now be reviewed. I'll leave the Modularity stuff for a separate PR.

**Comment by mzidek-gh** [comment]
Just one question. What does it mean for the user if fedora version is removed from the list? If I use fedora 30 after this patch, will I get some error message that the version is no longer supported?

**Comment by mgrabovsky** [comment]
The version list is only used on the stats page, so it has little real-world effect.

**Comment by mzidek-gh** [comment]
> The version list is only used on the stats page, so it has little real-world effect.

Ok, then I have no more comments. I have not tested the patches on a server, but I think they look safe enough to merge. So feel free to merge.

**Review by michalfabik — APPROVED** [review]

**Pull request merged**
