### PR TITLE
Support VMware snapshots

### LINKED ISSUE #290: retrace-server handling of vmware files: vmem + vmss file, and snapshots
Today retrace-server cannot handle submission of more than one file for kernel vmcores.  This often comes up with vmware and is described in "scenario A" of the following bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1785009#c0

The root of this issue is that the 'crash' tool can read the vmss file and looks for the corresponding vmem file in the same directory.  Unfortunately retrace-server cannot take more than one file for kernel crash dumps.

I think fixing this will require fixing the 'manager' interface as well as 'retrace-server-task create' command to handle this situation.

### PR DESCRIPTION
**Pull request by mkutlak**
<h5 align=center>NEW</h5>

NEW

## mock
- Switch from mock command `--shell` to `--chroot`.
- Use `--cwd crashdir` so crash can find `vmem` files for snapshots. (this requires `--chroot` command in mock)

## VMware snapshots
- New option `--vmem` in `retrace-server-task` to include VMEM file for snapshots.
- Snapshot files (vmsn, vmss) should have a same name (vmcore) and their respective extensions (vmsn, vmss, vmem) should **not** change.

Closes #290

### CODE REVIEW

**Comment by DaveWysochanskiRH** [comment]
Nice - I will grab this and put into some testing.

**Comment by DaveWysochanskiRH** [comment]
I'm getting an error:
$ retrace-server-task create
Traceback (most recent call last):
  File "/usr/bin/retrace-server-task", line 18, in <module>
    from retrace import SNAPSHOT_SUFFIXES
ImportError: cannot import name 'SNAPSHOT_SUFFIXES'

Also we need to have the .vmem file inside the 'crash' directory along with the vmsn file.

**Comment by ernestask** [comment]
+1 on the improved layout on the page.

**Comment by DaveWysochanskiRH** [comment]
Testing now...

**Comment by DaveWysochanskiRH** [comment]
That gets further, but not quite there.  I'm going to send you an email - I have a system we can test with and it's semi setup with CD now after you push to a branch, though testing is manual it helps.

The manager page works ok assuming you specify the kernel version.  Unfortunately I think the kernelver can only be detected from the vmem file, which is exactly opposite how the code works I think.  In any case, it looks like the web UI still is missing the vmem file in the same directory because I get this:

```
vmw: Memory dump is not part of this vmss file.
vmw: Try to locate the companion vmem file ...
 
crash: /cores/retrace/tasks/120015332/crash/vmcore: initialization failed

```

Running from the commandline I get an error and backtrace in /var/log/httpd/ssl_error_log
```
mod_wsgi (pid=9767): Exception occurred processing WSGI script '/usr/share/retrace-server/manager.wsgi'.
Traceback (most recent call last):
File "/usr/share/retrace-server/manager.wsgi", line 314, in application
  task.add_remote(POST[b"custom_url"][0].decode('utf-8'))
KeyError: b'custom_url'
mod_wsgi (pid=9770): Exception occurred processing WSGI script '/usr/share/retrace-server/manager.wsgi'.

```

**Comment by DaveWysochanskiRH** [comment]
Thanks for working on this.  Nice job on this so far!

**Comment by DaveWysochanskiRH** [comment]
Testing now...

**Comment by DaveWysochanskiRH** [comment]
I'm getting a weird error now after c4e9312 and even forcing kernelver no longer works.  I'll email you the task and keep looking.

**Comment by DaveWysochanskiRH** [comment]
Ok this:
+        self._vmem_path = os.join.path(self._crashdir, "vmcore.vmem")

Should be
+        self._vmem_path = os.path.join(self._crashdir, "vmcore.vmem")

I think - testing now.

**Comment by mkutlak** [comment]
> Ok this:
> 
>     * ```
>          self._vmem_path = os.join.path(self._crashdir, "vmcore.vmem")
>       ```
> 
> 
> Should be
> 
>     * ```
>          self._vmem_path = os.path.join(self._crashdir, "vmcore.vmem")
>       ```
> 
> 
> I think - testing now.

Fixed.

**Comment by DaveWysochanskiRH** [comment]
Thanks, pulling and re-testing, and looks good so far.  Need to do a few more tests...

**Comment by DaveWysochanskiRH** [comment]
As far as I can tell this is very good to merge!  Thanks for your work on this - many people will appreciate the work!

**Comment by DaveWysochanskiRH** [comment]
These latest patches break the functionality again, and I am getting this error:

> [2020-03-25 11:28:00] [D] unknown file type, unpacking finished
> [2020-03-25 11:28:00] [E] 'RetraceTask' object has no attribute 'set_vmcore'

**Comment by mkutlak** [comment]
> These latest patches break the functionality again, and I am getting this error:
> 
> > [2020-03-25 11:28:00] [D] unknown file type, unpacking finished
> > [2020-03-25 11:28:00] [E] 'RetraceTask' object has no attribute 'set_vmcore'

Fixed now. 

I removed the function but I've missed this one usage.

**Comment by DaveWysochanskiRH** [comment]
Latest changes look good again!  Thanks for the quick response.

**Pull request merged**
