### PR TITLE
Improve code culture

### PR DESCRIPTION
**Pull request by mgrabovsky**
* Proper escaping in regex string using `br"…"`.
* Make Pylint not warn about missing docstrings.
* Rename some variable in order to conform to Pylint rules.
* Some Pythonic code style improvements.
* Add a few type annotations here and there.
* Pass `check=False` explicitly to `subprocess.run()`.

### CODE REVIEW

**Comment by DaveWysochanskiRH** [comment]
Maybe you already know this but I got this Traceback with retrace-server-task create:
~~~
Traceback (most recent call last):
  File "/usr/bin/retrace-server-task", line 21, in <module>
    from retrace.retrace import add_snapshot_suffix
  File "/usr/lib/python3.6/site-packages/retrace/__init__.py", line 7, in <module>
    from . import retrace_worker
  File "/usr/lib/python3.6/site-packages/retrace/retrace_worker.py", line 13, in <module>
    from typing import Any, Dict, List, ModuleType, Optional, Tuple, Union
ImportError: cannot import name 'ModuleType'
~~~

**Comment by mgrabovsky** [comment]
Thanks for the catch.

**Comment by mgrabovsky** [comment]
Ready for review now.

**Comment by DaveWysochanskiRH** [comment]
Ran this through my dev systems (vmcores only, RetraceEnvironment = native)and didn't see any problems.

**Comment by mgrabovsky** [comment]
Thanks for the check, David.

**Review by michalfabik — APPROVED** [review]

**Comment by michalfabik** [comment]
LGTM

**Pull request merged**
