### PR TITLE
Remove old test, create new one

### PR DESCRIPTION
**Pull request by mgrabovsky**
Remove an old attempt at an integration test, which didn't work reliably anyway. Create a few new unit tests for the Podman backend class.

Moreover, fix a bug found by the test. An off-by-one error made the short container ID one character too short.

### CODE REVIEW

**Comment by mgrabovsky** [comment]
There's something wrong with the tests in the EPEL 8 build, so let's keep this open for now. I'll get back to it later.

**Comment by msrb** [comment]
I was able to run the tests successfully on my Fedora 34 workstation (outside of RPM). I can try on RHEL 8 (+EPEL) as well.

**Comment by msrb** [comment]
So far, it's +1 from me. Let's test that EPEL further.

**Comment by mgrabovsky** [comment]
@msrb I've fixed the tests on EPEL (more precisely, for Python 3.8). Could you please provide your green check mark? :)

**Review by msrb — APPROVED** [review]
LGTM :wink: Good catch with the older Python in RHEL 8.

**Pull request merged**
