### PR TITLE
Codestyle

### PR DESCRIPTION
**Pull request by matejkudera**
Changing code style.

### CODE REVIEW

**Comment by xsuchy** [comment]
test this please

**Comment by marusak** [comment]
> test this please

I would be genuinely surprised if something happened:) We do not have tests for RS yet ready.

**Comment by xsuchy** [comment]
:). OK. Merging as it looks good to me.

**Comment by marusak** [comment]
However I can test this manually. (sudo make check and bit of manual work). Will do that later today

**Pull request merged**
