### PR TITLE
Add commandline client

### PR DESCRIPTION
**Pull request by marusak**
This commit implements commandline client for creating, getting and
setting tasks.

Signed-off-by: Matej Marusak <mmarusak@redhat.com>

### CODE REVIEW

**Comment by marusak** [comment]
@mkutlak Could you please test this and let me know if you find any problems? Thanks.

**Comment by xsuchy** [comment]
Can you write it python3 friendly (so future migration is easier)? I.e. do not use xrange. Do not use bare except. And there are some style issue (pylint-3 is your friend).

**Comment by jfilak** [comment]
I thought the retrace-server client is already implemented:
https://github.com/abrt/abrt/blob/master/src/plugins/abrt-retrace-client.c

**Comment by marusak** [comment]
> I thought the retrace-server client is already implemented:
https://github.com/abrt/abrt/blob/master/src/plugins/abrt-retrace-client.c

Yeah, when I first got into this, I also was proposing that retrace-client exists. But this code does much more.
Few of them:
- Support of manager and ftp tasks (the main request from @DaveWysochanskiRH)
- Support for kerberos
- Support for interactive tasks (great for debugging)
- Does not need valid dumpdir (the abrt's script requires some other files such as 'type' and 'time'
- Get and Set options for different fields (status, email, caseno...)

**Comment by jfilak** [comment]
Alright then. So I propose to create a separate package for the client and drop the ABRT's client. There is no need to maintain two clients, or do I miss something?

**Comment by jfilak** [comment]
Maybe it is not such a good idea. ABRT client does some tasks specific only to ABRT - for example checking the correctness of the directory contents based on the problem type.

**Comment by DaveWysochanskiRH** [comment]
Hi yeah the original bug is https://bugzilla.redhat.com/show_bug.cgi?id=1396608 (I just added jakub@thefilaks.net on CC list so you can see it Jakub)
The main needs are:
1. to submit a local vmcore (kernel core) to the local retrace-server
2. handle kerberos (this was a requirement that came shortly after the bug was filed due to added security requirements)

**Comment by DaveWysochanskiRH** [comment]
I think the use case is slightly different between this and abrt-retrace-client, but agree they are similar.

**Comment by marusak** [comment]
> Alright then. So I propose to create a separate package

I agree with this part. It would be nice to have all cli actions from RS under one package. Or maybe even better create one RS cli and make actions pluginable as it is in FaF. But that is for some later.

>  drop the ABRT's client. There is no need to maintain two clients, or do I miss something?
Maybe it is not such a good idea. ABRT client does some tasks specific only to ABRT - for example checking the correctness of the directory contents based on the problem type.

Yeah, it is not such a good idea. We probably could merge into one, but I think the way there are today is fine. ABRT's one does things that are required from ABRT's perspective, and this does thinks more general for RS.

**Comment by marusak** [comment]
@xsuchy wrote:

> Can you write it python3 friendly (so future migration is easier)? I.e. do not use xrange. Do not use bare except. And there are some style issue (pylint-3 is your friend).

Sure I can. The only non-python3 thing was `xrange`. Changed it.
This is weird, I have pylint both on my work computer and my personal computer. It seemed OK on one and second one displayed quite a few problems. Fixed them (except 3 minor those I dont care about).

**Pull request merged**
